spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/espiel_spring_cloud_aws
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    stack:
      auto: false
    region:
      static: us-east-1

aws:
  s3:
    bucket: espiel-spring-cloud-aws-s3